#!/usr/bin/env python3
"""
生成 YOLO 格式的 data.yaml 配置文件。

从已有的 images/ + labels/（+ 可选 masks/）目录生成 train/ val/ 拆分和 data.yaml。

用法:
  # 统一目录，自动划分 train/val（含 masks）
  python src/ommateum/models/identify/generate_data_yaml.py \
      --images /path/to/dataset/images \
      --labels /path/to/dataset/labels \
      --names "scratch,crack" \
      --output /path/to/dataset/data.yaml \
      --val_split 0.1

  # val_split=0 时也生成 train/ 目录（主程序对路径敏感）
  python src/ommateum/models/identify/generate_data_yaml.py \
      --images /path/to/dataset/images \
      --labels /path/to/dataset/labels \
      --names "scratch,crack" \
      --output /path/to/dataset/data.yaml

  # 手动指定 train/val
  python src/ommateum/models/identify/generate_data_yaml.py \
      --train_images /data/train/images \
      --train_labels /data/train/labels \
      --val_images /data/val/images \
      --val_labels /data/val/labels \
      --names "scratch,crack" \
      --output /data/data.yaml

注：COCO JSON → YOLO labels 转换已解耦到 coco2yolo.py。
"""

import argparse
import os
import random
import shutil
from pathlib import Path
from typing import List, Optional, Tuple

IMAGE_EXTS = {".jpg", ".jpeg", ".png", ".bmp", ".tiff", ".tif", ".webp"}


def generate_data_yaml(
    output: str,
    names: List[str],
    train_images: Optional[str] = None,
    train_labels: Optional[str] = None,
    val_images: Optional[str] = None,
    val_labels: Optional[str] = None,
    images: Optional[str] = None,
    labels: Optional[str] = None,
    masks: Optional[str] = None,
    val_split: float = 0.0,
    seed: int = 42,
) -> str:
    """根据图片和标注目录生成 YOLO data.yaml，同步拆分 train/val。

    Args:
        output: 输出的 data.yaml 文件路径。
        names: 类别名称列表。
        train_images / train_labels: 模式 B — 手动指定 train 集路径。
        val_images / val_labels: 模式 B — 手动指定 val 集路径。
        images / labels: 模式 C — 统一目录，通过 val_split 自动划分。
        masks: 掩码目录，默认取 images 同级的 masks/（存在则拷贝到 train/val）。
        val_split: 验证集划分比例 (0.0~1.0)。
        seed: 随机种子。
    """
    output = os.path.abspath(output)
    output_dir = os.path.dirname(output)
    os.makedirs(output_dir, exist_ok=True)

    # ── 推断 masks 目录 ──
    if masks is None and images:
        inferred = os.path.join(os.path.dirname(os.path.abspath(images)), "masks")
        masks = inferred if os.path.isdir(inferred) else None
    elif masks is not None and not os.path.isdir(masks):
        print(f"[WARN] masks 目录不存在，跳过: {masks}")
        masks = None

    # ── 模式 B: 手动指定 train/val ──
    if train_images and train_labels:
        train_img_abspath = os.path.abspath(train_images)
        train_lbl_abspath = os.path.abspath(train_labels)
        val_img_abspath = os.path.abspath(val_images) if val_images else train_img_abspath
        val_lbl_abspath = os.path.abspath(val_labels) if val_labels else train_lbl_abspath
    else:
        # ── 模式 C: 统一目录 + 自动划分 ──
        if not images or not labels:
            raise ValueError("必须提供 --images/--labels 或 --train_images/--train_labels")
        images = os.path.abspath(images)
        labels = os.path.abspath(labels)

        if val_split > 0:
            (train_img_abspath, val_img_abspath,
             train_lbl_abspath, val_lbl_abspath) = _split_train_val(
                images, labels, masks, output_dir, val_split, seed
            )
        else:
            train_img_abspath, train_lbl_abspath = _copy_all_to_train(
                images, labels, masks, output_dir
            )
            val_img_abspath = train_img_abspath
            val_lbl_abspath = train_lbl_abspath

    # ── 生成 YAML ──
    yaml_content = (
        f"# Auto-generated data.yaml for YOLO training\n"
        f"# Generated by generate_data_yaml.py\n"
        f"\n"
        f"path: {output_dir}\n"
        f"train: {train_img_abspath}\n"
        f"val: {val_img_abspath}\n"
        f"\n"
        f"nc: {len(names)}\n"
        f"names: {names}\n"
    )
    with open(output, "w", encoding="utf-8") as f:
        f.write(yaml_content)

    print(f"[OK] data.yaml 已生成: {output}")
    print(f"     类别数: {len(names)} → {names}")
    print(f"     train images: {train_img_abspath}")
    print(f"     train labels: {train_lbl_abspath}")
    print(f"     val   images: {val_img_abspath}")
    print(f"     val   labels: {val_lbl_abspath}")
    return output


def _copy_all_to_train(
    images_dir: str,
    labels_dir: str,
    masks_dir: Optional[str],
    output_dir: str,
) -> Tuple[str, str]:
    """val_split=0 时将所有数据复制到 train/ 目录。"""
    train_img_dir = os.path.join(output_dir, "train", "images")
    train_lbl_dir = os.path.join(output_dir, "train", "labels")
    os.makedirs(train_img_dir, exist_ok=True)
    os.makedirs(train_lbl_dir, exist_ok=True)

    img_files = sorted(
        f for f in os.listdir(images_dir)
        if Path(f).suffix.lower() in IMAGE_EXTS
    )
    _copy_files(images_dir, labels_dir, img_files, train_img_dir, train_lbl_dir)

    # masks 只流向 train/（val_split=0 时没有 val）
    if masks_dir:
        train_msk_dir = os.path.join(output_dir, "train", "masks")
        os.makedirs(train_msk_dir, exist_ok=True)
        _copy_masks(masks_dir, img_files, train_msk_dir)
        print(f"[val_split=0] 已生成 train/ 结构: train={len(img_files)} 张 (含 masks)")

    print(f"[val_split=0] 已生成 train/ 目录结构: train={len(img_files)} 张")
    return train_img_dir, train_lbl_dir


def _split_train_val(
    images_dir: str,
    labels_dir: str,
    masks_dir: Optional[str],
    output_dir: str,
    val_split: float,
    seed: int,
) -> Tuple[str, str, str, str]:
    """将 images / labels / masks 按比例随机拆分为 train / val。"""
    random.seed(seed)

    img_files = sorted(
        f for f in os.listdir(images_dir)
        if Path(f).suffix.lower() in IMAGE_EXTS
    )
    if not img_files:
        raise RuntimeError(f"images 目录中没有图片文件: {images_dir}")

    random.shuffle(img_files)
    split_idx = max(1, int(len(img_files) * (1 - val_split)))
    train_files = img_files[:split_idx]
    val_files = img_files[split_idx:]

    train_img_dir = os.path.join(output_dir, "train", "images")
    train_lbl_dir = os.path.join(output_dir, "train", "labels")
    val_img_dir = os.path.join(output_dir, "val", "images")
    val_lbl_dir = os.path.join(output_dir, "val", "labels")

    dirs = [train_img_dir, train_lbl_dir, val_img_dir, val_lbl_dir]
    if masks_dir:
        train_msk_dir = os.path.join(output_dir, "train", "masks")
        val_msk_dir = os.path.join(output_dir, "val", "masks")
        dirs.extend([train_msk_dir, val_msk_dir])
    for d in dirs:
        os.makedirs(d, exist_ok=True)

    _copy_files(images_dir, labels_dir, train_files, train_img_dir, train_lbl_dir)
    _copy_files(images_dir, labels_dir, val_files, val_img_dir, val_lbl_dir)

    if masks_dir:
        _copy_masks(masks_dir, train_files, train_msk_dir)
        _copy_masks(masks_dir, val_files, val_msk_dir)

    extra = " (含 masks)" if masks_dir else ""
    print(f"[自动划分] train={len(train_files)} 张, val={len(val_files)} 张 "
          f"(split={val_split}){extra}")
    return train_img_dir, val_img_dir, train_lbl_dir, val_lbl_dir


def _copy_files(
    src_img: str,
    src_lbl: str,
    files: List[str],
    dst_img: str,
    dst_lbl: str,
) -> None:
    """复制图片及对应 YOLO label 到目标目录。"""
    for fname in files:
        shutil.copy2(os.path.join(src_img, fname), os.path.join(dst_img, fname))
        stem = Path(fname).stem
        lbl_path = os.path.join(src_lbl, f"{stem}.txt")
        if os.path.exists(lbl_path):
            shutil.copy2(lbl_path, os.path.join(dst_lbl, f"{stem}.txt"))


def _copy_masks(
    src_msk: str,
    files: List[str],
    dst_msk: str,
) -> None:
    """复制与图片同名的掩码文件到目标目录。"""
    for fname in files:
        stem = Path(fname).stem
        for ext in [".png", ".jpg", ".jpeg", ".bmp"]:
            msk_path = os.path.join(src_msk, f"{stem}{ext}")
            if os.path.exists(msk_path):
                shutil.copy2(msk_path, os.path.join(dst_msk, f"{stem}{ext}"))
                break


# ── CLI ──
def parse_args():
    parser = argparse.ArgumentParser(description="生成 YOLO data.yaml 配置文件")
    # 模式 B: 手动指定 train/val
    parser.add_argument("--train_images", default=None, help="训练集图片目录")
    parser.add_argument("--train_labels", default=None, help="训练集标注目录（YOLO .txt）")
    parser.add_argument("--val_images", default=None, help="验证集图片目录")
    parser.add_argument("--val_labels", default=None, help="验证集标注目录")
    # 模式 C: 统一目录
    parser.add_argument("--images", default=None, help="图片目录")
    parser.add_argument("--labels", default=None, help="标注目录（YOLO .txt）")
    parser.add_argument("--val_split", type=float, default=0.0,
                        help="验证集比例 (0.0~1.0)")
    # 通用
    parser.add_argument("--names", default=None,
                        help="类别名称，逗号分隔")
    parser.add_argument("--output", default="dataset/data.yaml",
                        help="输出 data.yaml 路径")
    parser.add_argument("--seed", type=int, default=42,
                        help="随机种子（train/val 划分用）")
    return parser.parse_args()


if __name__ == "__main__":
    args = parse_args()

    if not args.names:
        raise ValueError("--names 不能为空")
    names_list = [n.strip() for n in args.names.split(",") if n.strip()]
    if not names_list:
        raise ValueError("--names 不能为空")

    generate_data_yaml(
        output=args.output,
        names=names_list,
        train_images=args.train_images,
        train_labels=args.train_labels,
        val_images=args.val_images,
        val_labels=args.val_labels,
        images=args.images,
        labels=args.labels,
        val_split=args.val_split,
        seed=args.seed,
    )
